server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/주문관리/**, 
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/배송관리/**, 
        - id: product
          uri: http://localhost:8083
          predicates:
            - Path=/재고관리/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/주문관리/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/배송관리/**, 
        - id: product
          uri: http://product:8080
          predicates:
            - Path=/재고관리/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
